variable "common_tags" {}
variable "environment" {}
variable "project" {}
variable "public_subnet_ids" {}
variable "private_subnet_ids" {}
variable "vpc_id" {}
variable "base_cidr_block" {}
variable "acm_cert_arn" {}
variable "eice_ssh_id" {}
variable "rds_username" {}
variable "rds_password" {}
variable "rds_db_name" {}
variable "multi_az" {}
